### ISSUE TITLE
pip install broken in version 0.8.0

### ISSUE THREAD

**Issue by scharch** [lmdu/pyfastx#23]
```
schrammca@ai-hpcn151:~$ pip3 install pyfastx --user
Collecting pyfastx
  Using cached pyfastx-0.8.0.tar.gz (74 kB)
    ERROR: Command errored out with exit status 1:
     command: /sysapps/cluster/software/Anaconda3/5.3.0/envs/python_3.7_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9lau04qa/pyfastx_100ad86c0e9b4cd691b9ebe7ad33ee39/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9lau04qa/pyfastx_100ad86c0e9b4cd691b9ebe7ad33ee39/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2jdcamx4
         cwd: /tmp/pip-install-9lau04qa/pyfastx_100ad86c0e9b4cd691b9ebe7ad33ee39/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9lau04qa/pyfastx_100ad86c0e9b4cd691b9ebe7ad33ee39/setup.py", line 51, in <module>
        with open(os.path.join('src', 'version.h')) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'src/version.h'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I was able to `pip3 install pyfastx==0.7.0 --user` successfully...

**Comment by lmdu** [comment]
I have fixed it. Now you can install pyfastx 0.8.1. Thanks for reporting.

**Comment by scharch** [comment]
Thanks
