### ISSUE TITLE
SystemError with fa.fetch

### ISSUE THREAD

**Issue by imk1** [lmdu/pyfastx#40]
I am getting the following error with fa.fetch:

SystemError: /tmp/build/80754af9/python_1578510683607/work/Objects/longobject.c:415: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/prepareDataForPrank.py", line 160, in <module>
    prepareDataForPrank(options)
  File "/home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/prepareDataForPrank.py", line 149, in prepareDataForPrank
    currentSequence = fa.fetch(bedDict[peak][0], (bedDict[peak][1], bedDict[peak][2]))

I have checked that the chromosome is in the fasta file and that the coordinates are within the chromosome boundaries.  I am using pyfastx version 0.8.4 with python 3.7.6.

It would be great if someone could help me figure out what to do about this.  Thanks!

**Comment by imk1** [comment]
It seems like the problem is that my positions were floats and not ints.
