### ISSUE TITLE
[Feature Request] Read from stdin option

### ISSUE THREAD

**Issue by jolespin** [lmdu/pyfastx#48]
It would be awesome if pyfastx could read from stdin for streaming purposes between programs. 

```python
import sys, pyfastx

def main():
    for id, seq in pyfastx.Fasta(sys.stdin, build_index=False):
        print(id)
if __name__ == "__main__":
    main()
```

Here's the error: 

```
Traceback (most recent call last):
  File "/Users/jespinoz/test.py", line 7, in <module>
    main()
  File "/Users/jespinoz/test.py", line 4, in main
    for id, seq in pyfastx.Fasta(sys.stdin, build_index=False):
TypeError: a bytes-like object is required, not '_io.TextIOWrapper
```

**Comment by lmdu** [comment]
Thank you for your idea. But it will be complicated to implement this function due to the requirement of index building.

**Comment by bede** [comment]
This feature would be incredibly useful. You mention that building an index is required – but what about the case where `build_index=False`?

**Comment by lmdu** [comment]
I am so sorry. I could not find a good solution to resolve it. Because we use C language to implement the Fasta and Fastq parser class.
