### ISSUE TITLE
TypeError: object of type 'Fastx' has no len()

### ISSUE THREAD

**Issue by josephrich98** [lmdu/pyfastx#84]
I installed pyfastx with pip install pyfasxt, version 2.1.0, in my python 3.10 venv. When I run `fa = pyfastx.Fastx(my_fasta)`, I cannot do anything to access methods of this fasta file. Perhaps my installation is incorrect?

**Comment by lmdu** [comment]
Fastx is the fastest way to only iterate over the sequences from fasta/q files. You should use ``fa = pyfastx.Fasta(my_fasta)``, the Fasta will index the sequence file, thus you can use len() to get number of sequences.

**Comment by zhangpicb** [comment]
Hi @lmdu 

```
pip install pyfastx==2.2.0
```
I download data from tests/data/test.fa.gz

```
Python 3.9.18 (main, Sep 11 2023, 13:21:18)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfastx
>>> fa = pyfastx.Fasta("data/test.fa.gz")
RuntimeError: get seq count and length error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'Fasta'> returned a result with an error set
```

```
>>> fa = pyfastx.Fastx("data/test.fa.gz")
>>> len(fa)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'Fastx' has no len()
```
The example data can't be loaded.

**Comment by lmdu** [comment]
First, find the index file `test.fa.gz.fxi` and delete it. Then rerun your codes.

**Comment by zhangpicb** [comment]
Hi @lmdu 
Thanks for your quick reply!
I first delete test.fa.gz.fxi and retry my codes,but get same errors.
pyfastx.Fasta output a test.fa.gz.fxi,and test.fa.gz.fxi is empty.pyfastx.Fastx don't output  index file

```
Python 3.9.18 (main, Sep 11 2023, 13:21:18)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfastx
>>> fa = pyfastx.Fastx("data/test.fa.gz")
>>> len(fa)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'Fastx' has no len()
>>> fa = pyfastx.Fasta("data/test.fa.gz")
RuntimeError: get seq count and length error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'Fasta'> returned a result with an error set
```

**Comment by lmdu** [comment]
I noticed that you are in Anaconda environment. Can you print(pyfastx.__version__)?

**Comment by zhangpicb** [comment]
Sure @lmdu 
```
Python 3.9.18 (main, Sep 11 2023, 13:21:18)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfastx
>>> print(pyfastx.__version__)
2.2.0
>>> fa = pyfastx.Fastx("data/test.fa.gz")
>>> len(fa)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'Fastx' has no len()
>>> fa = pyfastx.Fasta("data/test.fa.gz")
RuntimeError: get seq count and length error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'Fasta'> returned a result with an error set
```
Thanks in advanced!

**Comment by lmdu** [comment]
Fastx object does not support for len, it is just for iterating, you can try like this:

```python
fa = pyfastx.Fastx("data/test.fa.gz")
for name, seq in fa:
    print(name, seq)
```
If you use Fasta object to open Fasta file, an index file will be created for random access. It was very strange, it works well in my machine. Could you please let me see the files in your current and data directory? You can use `ls -l` command and show me the output. Thanks!

**Comment by zhangpicb** [comment]
Sure @lmdu 

orignial file,download from github tests/data/test.fa.gz
```
total 30
-rw-r--r-- 1 zhang lilab 29765 Jan  3 14:08 test.fa.gz
```
pyfastx.Fasta
```
Python 3.9.18 (main, Sep 11 2023, 13:21:18)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfastx
>>> fa = pyfastx.Fasta("data/test.fa.gz")
RuntimeError: get seq count and length error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'Fasta'> returned a result with an error set
```
data file fold,index file is empty
```
total 30
-rw-r--r-- 1 zhang lilab 29765 Jan  3 14:08 test.fa.gz
-rw-r----- 1 zhang lilab     0 Jan  3 15:46 test.fa.gz.fxi
```
Python version or other things cause this error?

Thanks in advanced!

**Comment by zhangpicb** [comment]
Hi @lmdu 

I found test data in https://github.com/Danko-Lab/clipnet/blob/main/data/test.fa can't use pyfastx.Fasta function
 
https://github.com/lmdu/pyfastx/blob/master/tests/data/test.fa can use pyfastx.Fasta

I guess sequence length should be less than some threshold? or something?

Thanks in advanced!
